### ISSUE TITLE
Lab6: templates/service.yamlがreadme.mdと異なる

### ISSUE THREAD

**Issue by kyokonishito** [ibm-cloud-labs/iks-handson#14]
ハンズオン参加者の方のtemplates/service.yamlは
[設定を変更する](https://github.com/ibm-cloud-labs/iks-handson/tree/master/Lab6#%E8%A8%AD%E5%AE%9A%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%99%E3%82%8B)の最初に表示されているtemplates/service.yamlと異なっているため、17行目がどこにあたるのかがわかりませんでした。
Helmのバージョンは2.14.1でした。
表示されているtemplates/service.yamlの17行目は`selector:`の下だったので、ハンズオン参加者の方のtemplates/service.yamlの`selector:`の下にいれてみましたが、`helm upgrade -f value-new.yaml sample ./mychart/`のコマンド実行でエラーが出ました。
<img width="524" alt="lab3_error" src="https://user-images.githubusercontent.com/40123488/61021524-e1ec4080-a3dc-11e9-94b9-51b25ec227f0.png">

**Comment by kota661** [comment]
helm v2.14で生成されるyamlに変更しました。

https://github.com/ibm-cloud-labs/iks-handson/commit/a712a41617d0893f381b10b515d7f0451465e7ee
