### ISSUE TITLE
Lab6: 最後のhelm upgrade -f value-new.yaml sample ./mychart/　でエラー

### ISSUE THREAD

**Issue by kyokonishito** [ibm-cloud-labs/iks-handson#15]
Lab6 [リソースを追加する](https://github.com/ibm-cloud-labs/iks-handson/tree/master/Lab6#%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B)の一番最後、`helm upgrade -f value-new.yaml sample ./mychart/`で以下のエラーが発生する。
`Error: UPGRADE FAILED: render error in "mychart2/templates/deployment.yaml": template: mychart2/templates/deployment.yaml:4:11: executing "mychart2/templates/deployment.yaml" at <include "mychart.ful...>: error calling include: template: no template "mychart.fullname" associated with template "gotpl"`

参考までに「チャートのtemplatesディレクトリにあるdeployment.yamlを編集します」という作業は、readme.mdに表示されているファイルの中身とまるまる置き換えでやっています。

**Comment by kota661** [comment]
利用されたhelmのVersionはいくつでしょうか？

> readme.mdに表示されているファイルの中身とまるまる置き換えでやっています。

Deployment.ymlの内容が大きく違う場合はバージョン違いの可能性があります
その場合、丸コピしてもバージョンごとにサポートされている記述が違うため動きません。
過去にあったのはAlpha版のV3を利用されているお客様が同様のエラーになっていたと思います

**Comment by kyokonishito** [comment]
Helmのバージョンはv2.7.2です。よろしくお願いします。

**Comment by kota661** [comment]
2.7は古すぎるのでまずは更新お願いします

**Comment by kyokonishito** [comment]
v2.14.2にアップグレードして無事うまく行きました。ご迷惑おかけしました。Closeします。
