### ISSUE TITLE
helm installを実行するとエラーとなる

### ISSUE THREAD

**Issue by kissyy** [ibm-cloud-labs/iks-handson#4]
Lab4でhelm installを実行すると以下のエラーが出る。
Error: release jpetstore-new failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"

**Comment by kota661** [comment]
https://cloud.ibm.com/docs/containers?topic=containers-integrations&locale=ja#helm
