### ISSUE TITLE
Lab3: kubernetes/redis-slave:v2のイメージがない

### ISSUE THREAD

**Issue by kyokonishito** [ibm-cloud-labs/iks-handson#5]
lab3の「11. Redis Slaveデータベースのdeploymentを作成します。」で使用する
redis-slave-deployment.yaml内の
kubernetes/redis-slave:v2のイメージがdockerhubに存在しないため、
「12. Redis Slaveデータベースの全てのPodが動作しているか確認します。」で
ErrImagePullのエラーになる。
```
$ kubectl get pods -l app=redis,role=slave
NAME                           READY   STATUS         RESTARTS   AGE
redis-slave-5db5dcfdfd-4d7pn   0/1     ErrImagePull   0          43s
redis-slave-5db5dcfdfd-gsck8   0/1     ErrImagePull   0          43s
$ kubectl logs redis-slave-5db5dcfdfd-4d7pn
Error from server (BadRequest): container "redis-slave" in pod "redis-slave-5db5dcfdfd-4d7pn" is waiting to start: image can't be pulled
```

**Comment by kota661** [comment]
めも
* Fork元でのIssues
  - https://github.com/IBM/kube101/issues/63
* 元ネタ
  - https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#start-up-the-redis-slaves

**Comment by kota661** [comment]
めも
* Fork元でのIssues
  - `https://github.com/IBM/kube101/issues/63`
* 元ネタ
  - https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#start-up-the-redis-slaves

**Comment by kota661** [comment]
@kyokonishito 消えていたDockerImageを元ネタのImageを使って、独自のDockerHubに登録し直しました。
こちらのプルリクをチェックして、問題なければ、マージし、このIssuesをクローズしてください。
https://github.com/ibm-cloud-labs/guestbook/pull/1

**Comment by kyokonishito** [comment]
@kota661 Write権限がないので
ibm-cloud-labs/guestbook#1
が私にはマージできないようです。問題なかったのでマージしていただけますか？(Approve済)
